#!/usr/bin/env node
/**
 * Post-deploy verification for cto/AdaptaLabs#158.
 *
 * cto/AdaptaLabs#158: the Kubera platform's ArgoCD push can fail silently -
 * the deploy job's trace logs "failed to push some refs" as a WARNING,
 * immediately follows it with "Pushed changes to the remote repository", and
 * exits 0. Every pipeline surface (the job, the `trigger-deployment-prod`
 * bridge, the parent pipeline) reports green while that half of the app never
 * rolled. This script is the in-repo mitigation: it polls what is actually
 * SERVED rather than trusting job exit codes, and turns a silent skip into a
 * red pipeline.
 *
 * This is NOT a fix for the platform bug - the real fix (fail the push,
 * retry on rejection) belongs to the Kubera platform component
 * (to-be-continuous/kubera) and is tracked in #158, which stays open.
 *
 * WHY A RELEASE GATE. `trigger-deployment-prod` runs unconditionally on every
 * push to main (see .gitlab-ci.yml's `$CI_COMMIT_REF_NAME =~ $PROD_REF`
 * rule), whether or not semantic-release cut a version. The downstream
 * dynamic pipeline (generated by `generate-environment-jobs`) sets
 * `APP_VERSION` from `$SEMREL_INFO_NEXT_VERSION` when a release IS due, and
 * falls back to `$SEMREL_INFO_LAST_VERSION` - the PREVIOUS release - when it
 * is not. So a `ci:`/`docs:`/`refactor:` merge still runs a "successful"
 * deploy, but it redeploys the same old image unchanged; the served revision
 * correctly stays whatever it already was, and $CI_COMMIT_SHA of THIS
 * pipeline never appears. Asserting a revision match on that pipeline would
 * be a false failure, not a caught bug - so this script only polls when
 * `SEMREL_INFO_NEXT_VERSION` (the same dotenv `check-release-will-deploy`
 * reads, from the `semantic-release-info` job) says a release was actually
 * cut.
 *
 * Usage (CI):
 *   CI_COMMIT_SHA=<sha> SEMREL_INFO_NEXT_VERSION=<version|empty> \
 *     node scripts/verify-deploy.mjs
 *
 * Usage (manual):
 *   node scripts/verify-deploy.mjs --sha <sha> [--base-url <url>]
 *
 * Exit 0 when nothing needed verifying, or when the deploy is confirmed live.
 * Exit 1, BY NAME, when the timeout is hit before both sides serve the
 * expected revision.
 */

const DEFAULT_BASE_URL = 'https://adaptalabs.kubera-playground.adaptavist.net';

// Pinned literals, not derived from each other - see scripts/verify-deploy.test.js,
// which asserts these exact numbers so a change to either is a visible diff.
export const DEFAULT_TIMEOUT_MS = 10 * 60 * 1000; // 10 minutes, per #158
export const DEFAULT_POLL_INTERVAL_MS = 15 * 1000; // 15 seconds

// Which deploy job's trace to point the reader at for each lagging side -
// the exact job names from #158's own trace (kubera-playground-backend /
// kubera-playground-frontend), not a paraphrase.
const DEPLOY_JOB_BY_SIDE = {
  api: 'kubera-playground-backend',
  web: 'kubera-playground-frontend'
};

/**
 * Whether this pipeline cut a release at all.
 *
 * `check-release-will-deploy.sh` treats a present-and-non-empty
 * SEMREL_INFO_NEXT_VERSION as "a release will be cut" (see ci/check-release-will-deploy.sh);
 * this mirrors that exact test so the two checks cannot silently disagree
 * about which commits deploy.
 */
export function releaseWillDeploy(nextVersion) {
  return typeof nextVersion === 'string' && nextVersion.trim() !== '';
}

async function fetchRevision(fetchImpl, url) {
  let res;
  try {
    res = await fetchImpl(url);
  } catch (err) {
    return { ok: false, error: `request failed: ${err.message}` };
  }

  let text;
  try {
    text = await res.text();
  } catch (err) {
    return { ok: false, error: `could not read response body: ${err.message}` };
  }

  const contentType = typeof res.headers?.get === 'function' ? res.headers.get('content-type') || '' : '';

  let body;
  try {
    body = JSON.parse(text);
  } catch {
    // The frontend's nginx serves the SPA fallback (index.html, HTTP 200) for
    // any pod that predates /version.json, so a JSON-parse failure here is
    // "not deployed yet", not a transport error - same reasoning as
    // verify-production.mjs's checkFrontend.
    return {
      ok: false,
      error: `not JSON (HTTP ${res.status}, content-type "${contentType || 'none'}"): ${text.slice(0, 120)}`
    };
  }

  return { ok: true, revision: typeof body.revision === 'string' ? body.revision : null, status: res.status };
}

function revisionMatches(result, expectedLower) {
  return Boolean(result.ok && result.revision && result.revision.toLowerCase() === expectedLower);
}

function describe(result) {
  if (!result.ok) return result.error;
  if (!result.revision) return 'responded with no revision field';
  return `revision=${result.revision}`;
}

function buildTimeoutMessage({ lagging, api, web, expectedSha, timeoutMs }) {
  const seconds = Math.round(timeoutMs / 1000);
  const sideLines = lagging
    .map((side) => {
      const result = side === 'api' ? api : web;
      const job = DEPLOY_JOB_BY_SIDE[side];
      return `  - ${side}: ${describe(result)} (expected ${expectedSha}) - grep the ${job} job's ` +
        `trace for "failed to push" and retry that job (see cto/AdaptaLabs#158)`;
    })
    .join('\n');

  return (
    `verify-deploy: timed out after ${seconds}s waiting for ${lagging.join(' and ')} ` +
    `to serve ${expectedSha}.\n${sideLines}`
  );
}

/**
 * Poll /api/health and /version.json until both report `expectedSha`, or
 * `timeoutMs` elapses.
 *
 * `fetchImpl` defaults to the global `fetch` (Node 20+); tests inject a fake
 * so no test makes a real HTTP call or waits the real interval.
 */
export async function pollDeploy({
  baseUrl,
  expectedSha,
  fetchImpl = fetch,
  timeoutMs = DEFAULT_TIMEOUT_MS,
  pollIntervalMs = DEFAULT_POLL_INTERVAL_MS,
  onAttempt
} = {}) {
  if (!baseUrl) throw new Error('pollDeploy: baseUrl is required');
  if (!expectedSha) throw new Error('pollDeploy: expectedSha is required');

  const expectedLower = expectedSha.trim().toLowerCase();
  const base = baseUrl.replace(/\/$/, '');
  const start = Date.now();

  for (;;) {
    // Cache-bust both requests: version.json is already `no-store`, but this
    // is belt-and-braces against any intermediate cache (CDN, proxy) that
    // does not honour it.
    const cb = Date.now();
    const [api, web] = await Promise.all([
      fetchRevision(fetchImpl, `${base}/api/health?cb=${cb}`),
      fetchRevision(fetchImpl, `${base}/version.json?cb=${cb}`)
    ]);

    const apiMatches = revisionMatches(api, expectedLower);
    const webMatches = revisionMatches(web, expectedLower);

    if (typeof onAttempt === 'function') {
      onAttempt({ api, web, apiMatches, webMatches, elapsedMs: Date.now() - start });
    }

    if (apiMatches && webMatches) {
      return { ok: true, api, web, elapsedMs: Date.now() - start };
    }

    const elapsedMs = Date.now() - start;
    if (elapsedMs >= timeoutMs) {
      const lagging = [];
      if (!apiMatches) lagging.push('api');
      if (!webMatches) lagging.push('web');
      return {
        ok: false,
        api,
        web,
        lagging,
        elapsedMs,
        message: buildTimeoutMessage({ lagging, api, web, expectedSha, timeoutMs })
      };
    }

    await new Promise((resolve) => setTimeout(resolve, pollIntervalMs));
  }
}

function parseArgs(argv) {
  const args = { sha: null, baseUrl: null };
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === '--sha') args.sha = argv[++i];
    else if (argv[i] === '--base-url') args.baseUrl = argv[++i];
  }
  return args;
}

async function main() {
  const cliArgs = parseArgs(process.argv.slice(2));
  const nextVersion = process.env.SEMREL_INFO_NEXT_VERSION;
  const expectedSha = cliArgs.sha || process.env.CI_COMMIT_SHA;
  const baseUrl = cliArgs.baseUrl || process.env.VERIFY_DEPLOY_BASE_URL || DEFAULT_BASE_URL;

  if (!releaseWillDeploy(nextVersion)) {
    console.log(
      'SKIP verify-deploy: SEMREL_INFO_NEXT_VERSION is empty, so this pipeline cut no ' +
        'release. trigger-deployment-prod still ran, but it redeployed the previous ' +
        'release unchanged (APP_VERSION falls back to SEMREL_INFO_LAST_VERSION) - there ' +
        'is no new revision to verify.'
    );
    process.exit(0);
  }

  if (!expectedSha) {
    console.error('FAIL verify-deploy: no commit sha given (CI_COMMIT_SHA or --sha).');
    process.exit(1);
  }

  console.log(
    `verify-deploy: release ${nextVersion} was cut from ${expectedSha}. Polling ${baseUrl} ` +
      `for up to ${Math.round(DEFAULT_TIMEOUT_MS / 1000)}s for both /api/health and ` +
      '/version.json to report it...'
  );

  const result = await pollDeploy({ baseUrl, expectedSha });

  if (result.ok) {
    console.log(
      `OK verify-deploy: api and web both serve ${expectedSha} ` +
        `(after ${Math.round(result.elapsedMs / 1000)}s).`
    );
    process.exit(0);
  }

  console.error(result.message);
  process.exit(1);
}

const isMain = process.argv[1] && import.meta.url === `file://${process.argv[1]}`;
if (isMain) {
  main();
}
